- .github/workflows/compile.yml
- .github/workflows/docs.yml
- .github/workflows/functional.yml
- .github/workflows/integration.yml
- .github/workflows/mutants.yml
- .github/workflows/unit.yml
This PR replaces all mention of `self-hosted` to `ubuntu-latest` the CI workflows.
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update
-   [ ] Refactor
-   [x] I have performed a self-review of my code.
-   [x] I have commented my code where necessary.
-   [x] I have updated the documentation if needed.
-   [x] My changes do not introduce new warnings.
-   [ ] I have added tests that prove my changes are effective or that my feature works.
-   [x] New and existing tests pass with my changes.
> fix: use github runner in all workflows

- Cargo.toml
- README.md
Fixes a link that was not formatted properly in the Readme.
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] Documentation update
-   [ ] Refactor
-   [ ] I have performed a self-review of my code.
-   [ ] I have commented my code where necessary.
-   [ ] I have updated the documentation if needed.
-   [ ] My changes do not introduce new warnings.
-   [ ] I have added tests that prove my changes are effective or that my feature works.
-   [ ] New and existing tests pass with my changes.
> docs: fix link display

- .github/workflows/build.yml
- .github/workflows/dependencies.yml
- .github/workflows/docs.yml
- .github/workflows/lint-actions.yml
- .github/workflows/lint.yml
- .github/workflows/security.yml
- .github/workflows/unit.yml
- .github/workflows/zizmor.yml
There is a new zizmor release that requires further hardening of the
permissions in the GH Actions workflows
> ci: update workflows to zizmor 1.2.X

- .cargo/config.toml
- .vscode/settings.json
> fix: vscode clippy not working

- .github/workflows/cron-nightly-rust.yml
- .github/workflows/cron-zizmor.yml
These CI jobs are automated cron jobs that run security analysis (`zizmor`) and update the rust nightly version to stop it becoming stale.
`strata` runs on day 1 of the month and I've seen that we are running on day 2 here in `strata-bridge`.
> ci: cron jobs from `strata`

- crates/btc-notify/src/client.rs
- crates/btc-notify/src/lib.rs
- crates/btc-notify/src/subscription.rs
> export Subscription directly from subscription module

- .github/PULL_REQUEST_TEMPLATE.md
Not every PR needs new tests. This PR updates the PR template to make this more clear.
N/A
N/A
> Update PR template wording

- Cargo.lock
Update openssl from 0.10.68 to 0.10.71
Closes: Dependabot alert https://github.com/alpenlabs/strata-bridge/security/dependabot/9
> update openssl from 0.10.68 to 0.10.71

- .cargo/config.toml
- crates/agent/src/operator.rs
- crates/tx-graph/src/lib.rs
- crates/tx-graph/src/peg_out_graph.rs
The first commit in this series edits the cargo/config.toml to make this repo compatible with ssh-based cloning.
The second commit in this series introduces a PegOutGraphSummary data structure that can be used to compress the PegOutGraph information to the minimum set of information required to recognize all transactions in a given PegOutGraph.
The third commit in this series removes the async property of the `PegOutGraph::generate` function since it no longer has a database dependency.
> Implement `PegOutGraphSummary` + de-async `PegOutGraph::generate`

- .dockerignore
- bin/secret-service/Dockerfile
- compose.yml
- docker/secret-service/Dockerfile
- docker/vol/secret-service/config.toml
Adds a dockerfile for the secret service
> add secret service dockerfile

- crates/rpc/src/lib.rs
> Fix parameter names in bridge monitoring trait

- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/contract_state_machine.rs
- crates/primitives/src/operator_table.rs
Implements a nagging process where we request p2p messages from our peers if they haven't given us what we need.
> implement p2p nagging during the DRT conversion process

- crates/duty-tracker/src/contract_manager.rs
Implements nag responses for all p2p messages. Also implements nagging for stake chain exchanges.
> implement nag response, and nag stake chain exchanges

- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/errors.rs
- crates/duty-tracker/src/tx_driver.rs
adds the `tx-driver` handle to the contract manager (and context).
Also does some error plumbing, and broadcast a TODO tx.
> contract manager: add tx-driver handle

- .github/workflows/lint.yml
- crates/db/src/inmemory/operator.rs
- crates/db/src/operator.rs
- crates/db/src/persistent/sqlite.rs
- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/contract_state_machine.rs
- crates/duty-tracker/src/errors.rs
- crates/duty-tracker/src/stake_chain_persister.rs
- crates/duty-tracker/src/stake_chain_state_machine.rs
- crates/duty-tracker/src/tx_driver.rs
- crates/stake-chain/src/transactions/stake.rs
- crates/tx-graph/src/peg_out_graph.rs
- migrations/20241113060253_init_schema.sql
- rust-toolchain.toml
This PR:
* Adds executor to advance the stake chain at every withdrawal assignment.
* Adds an additional contract event to advance the stake chain and rewires the STFs so that the stake chain is advanced first and the withdrawal fulfillment happens after that if the assignee matches.
@ProofOfKeags the contract events and the associated STFs need a closer look.
Closes STR-1204
> STR-1204 handle duty to advance the stake chain

- .codespellrc
- crates/duty-tracker/src/contract_state_machine.rs
> adds error information to TransitionErr

- Cargo.lock
Closes https://github.com/alpenlabs/strata-bridge/security/dependabot/11 Closes https://github.com/alpenlabs/strata-bridge/security/dependabot/12 Closes https://github.com/alpenlabs/strata-bridge/security/dependabot/13
> chore(deps): tokio crossbeam-channel openssl

- .github/workflows/build.yml
> chore: update sccache

- crates/bridge-proof/protocol/src/error.rs
- crates/bridge-proof/protocol/src/lib.rs
- crates/bridge-proof/protocol/src/statement.rs
> Str 1128 check deposit id and deposit txid

- crates/primitives/src/deposit.rs
- crates/primitives/src/scripts/metadata.rs
This PR updates the metadata output in the Deposit Transaction to hold the take back key of the user (as per the one in DRT) and the input amount. This data can be used to compute the prevout required to compute the transaction hash of the Deposit Transaction.
> Update Deposit Tx Metadata to include take back key and amount

- .github/workflows/build.yml
- .github/workflows/cron-nightly-rust.yml
- .github/workflows/cron-zizmor.yml
- .github/workflows/dependencies.yml
- .github/workflows/docs.yml
- .github/workflows/lint-actions.yml
- .github/workflows/lint.yml
- .github/workflows/security.yml
- .github/workflows/unit.yml
- .github/workflows/zizmor.yml
- zizmor.yml
This PR hash-pins all external workflows as per the default pinned usage policy in zimor >=1.6
> ci: hash-pin all external workflows

- crates/agent/src/operator.rs
- crates/tx-graph/src/peg_out_graph.rs
- crates/tx-graph/src/transactions/burn_payouts.rs
- crates/tx-graph/src/transactions/challenge.rs
- crates/tx-graph/src/transactions/claim.rs
- crates/tx-graph/src/transactions/covenant_tx.rs
- crates/tx-graph/src/transactions/disprove.rs
- crates/tx-graph/src/transactions/payout.rs
- crates/tx-graph/src/transactions/payout_optimistic.rs
- crates/tx-graph/src/transactions/post_assert.rs
- crates/tx-graph/src/transactions/pre_assert.rs
- crates/tx-graph/src/transactions/slash_stake.rs
This PR updates the `CovenantTx` trait so that it returns a [fixed-length] array of witnesses and sighashes. This trait is then implemented for each of the transactions that require an N-of-N signature.
> Refactor input-related methods in tx wrapper types to return arrays

- Cargo.lock
- crates/agent/src/operator.rs
- crates/duty-tracker/src/contract_state_machine.rs
- crates/primitives/src/wots.rs
- crates/tx-graph/Cargo.toml
- crates/tx-graph/src/peg_out_graph.rs
This PR replaces the `wots` type inside the `PogInput` with those from the `strata-p2p-types`. The `connectors` crate still uses the types from `strata-bridge-primitives::wots` to maintain compatibility with the BitVM scripts. `Into` and `TryInto` have been implemented to convert from one type to another.
> feat(tx-graph): make PogInput serde compatible by using strata-p2p-types

- crates/secret-service-client/src/wots.rs
- crates/secret-service-proto/src/v1/traits.rs
- crates/secret-service-proto/src/v1/wire.rs
- crates/secret-service-server/src/lib.rs
Corrects the wording in the wots signer to be a generic txid/vout, not a stake txid/vout.
> fix(s2) reword wots signer spec

- Cargo.lock
- Cargo.toml
- bin/assert-splitter/Cargo.toml
- bin/dev-cli/Cargo.toml
- bin/dev-cli/src/bridge_out/withdrawal.rs
- bridge-guest-builder/Cargo.toml
- bridge-guest-builder/bridge-guest/Cargo.lock
- bridge-guest-builder/bridge-guest/Cargo.toml
- crates/connectors/src/connector_a3.rs
> Replace sha256 with blake3 in verification of public values

- .github/workflows/build.yml
- .github/workflows/cron-nightly-rust.yml
- .github/workflows/cron-zizmor.yml
- .github/workflows/dependencies.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/unit.yml
- .github/workflows/zizmor.yml
This PR updates the hash pins to resolve the code scanning issues reported by Github: https://github.com/alpenlabs/strata-bridge/security/code-scanning. 
Maybe we should have a cron job for this as well?
> sec(ci): update hash-pins to remove imposter commits

- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/contract_state_machine.rs
This PR is a first draft of parallelizing graph generation inside of a single CSM. Currently it takes a very naive approach where we do not consider any thread pools, nor do we use async/green threads. This choice was made for expediency so we could get immediate practical benefits in testing while we consider the best way to handle this at larger scales.
> Parallelize graph generation

- bin/alpen-bridge/src/mode/operator.rs
dns lookup for secret service server address
> fix: dns lookup for secret service server address

- bin/alpen-bridge/src/config.rs
- crates/btc-notify/src/client.rs
- crates/duty-tracker/src/contract_manager.rs
- docker/vol/alpen-bridge-1/config.toml
- docker/vol/alpen-bridge-2/config.toml
- docker/vol/alpen-bridge-3/config.toml
This PR makes it such that we don't treat the RPC notion of "current" differently from the zmq notion of "current".
Commits are atomic.
> Only RPC sync to the buried height

- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/contract_state_machine.rs
> detach synthetic event handling from csm

- bin/dev-bridge/src/bootstrap.rs
- crates/agent/src/operator.rs
- crates/db/src/inmemory/operator.rs
- crates/db/src/inmemory/public.rs
- crates/db/src/operator.rs
- crates/db/src/persistent/models.rs
- crates/db/src/persistent/sqlite.rs
- crates/db/src/persistent/types.rs
- crates/db/src/public.rs
- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/contract_persister.rs
- crates/duty-tracker/src/executors/deposit.rs
- crates/primitives/src/scripts/taproot.rs
- crates/test-utils/src/musig2.rs
- migrations/20241113060253_init_schema.sql
Span out of #150, all the other non-related stuff that fixes database trait are here.
Janitor work in a lot of crates: `agent`, `db` etc.
> Fix databases

- crates/duty-tracker/src/stake_chain_persister.rs
Fixes the `StakeChainPersister` duplicate logs
> log: fix duplicate StakeChainPersister logs

- crates/duty-tracker/src/contract_state_machine.rs
a more informative log: when a reassignment happens, specify the deposit idx
> log assignment idx on re-assignment

- crates/duty-tracker/src/contract_manager.rs
Reverts #171.
The thing works, tested deposits and restarts before the nonces are shared.
STR-1540
> revert: Actor-based parallelism

- crates/bridge-proof/protocol/src/statement.rs
This PR clarifies the purpose of `REQUIRED_NUM_HEADERS_AFTER_FULFILLMENT` constant and the reason why its value is set in the way it is.
This PR was created as per a thread on Slack.
> docs(bridge-proof): clarify the intent behind the current value of header length

- bin/alpen-bridge/src/rpc_server.rs
For the bridge monitoring API, we should only return active graphs claims for the `claims` RPC method.
No matching with `_` because it "introduces demons"™.
STR-1556
> fix(rpc): only return active graph's claim txids.

- Cargo.lock
- crates/algebra/Cargo.toml
- crates/algebra/src/bijection.rs
- crates/algebra/src/category.rs
- crates/algebra/src/lib.rs
- crates/algebra/src/predicate.rs
- crates/algebra/src/state_machine.rs
> Algebra gadgets

- bin/alpen-bridge/src/config.rs
- bin/alpen-bridge/src/mode/operator.rs
- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/executors/config.rs
- crates/duty-tracker/src/executors/mod.rs
- crates/duty-tracker/src/executors/optimistic_withdrawal.rs
- docker/vol/alpen-bridge-1/config.toml
- docker/vol/alpen-bridge-2/config.toml
- docker/vol/alpen-bridge-3/config.toml
This is an admin-only PR that takes the commits we added for STR-1589 and puts them in main instead of the release branch. This was a TN2 item that was incorrectly merged into the release branch. Those commits will be stripped from the release branch
> BACKPORT: STR-1589 -> main

- crates/duty-tracker/src/contract_manager.rs
This PR fixes a bug in the nagging logic where the nag request for root partials was being constructed but not added to the overall list of nags.
> fix(duty-tracker): actually nag for root partials

- crates/duty-tracker/src/contract_manager.rs
This is a backport of the changes made in PR #234.
> [BACKPORT 234] fix(duty-tracker): actually nag for root partials

- crates/bridge-proof/primitives/src/tx.rs
Fixes a typo in `bridge-proof` tests.
Originally reported in #240.
None
> fix(bridge-proof): typo in tests

- Cargo.toml
- bin/alpen-bridge/src/rpc_server.rs
- crates/rpc/src/types.rs
Avoid cloning the `cache` in the RPC server on `alpen-bridge`.
`just pr` got some `taplo` formatting in one forsaken `Cargo.toml` so I'm adding this in a different commit.
STR-1625
> perf(alpen-bridge): don't clone the `cache`!

- .gitignore
- docs/secret-service.md
Adds additional detailed documentation for the Secret Service.
STR-1651
> feat(s2): add secret-service.md

- .github/CODEOWNERS
> meta: update CODEWONERS
