alpenlabs/strata-bridge

- Cargo.lock
hashbrown to 0.15.2
rustls to 0.23.19
closes https://github.com/alpenlabs/strata-bridge-poc/security/dependabot/5
closes https://github.com/alpenlabs/strata-bridge-poc/security/dependabot/6
closes https://github.com/alpenlabs/strata-bridge-poc/security/dependabot/4
> chore(deps): rustls and hashbrown

- Cargo.lock
- Cargo.toml
- bridge-guest-builder/bridge-guest/Cargo.lock
- crates/bridge-proof/protocol/Cargo.toml
- crates/bridge-proof/snark/Cargo.toml
- crates/bridge-proof/test-utils/Cargo.toml
- crates/btcio/src/error.rs
Gets rid of the `bitvm` branch of rust-bitcoin.
Depends on https://github.com/alpenlabs/strata/pull/548.
Also removes all `0.31.X` versions of `rust-bitcoin` in the `Cargo.lock`.
This paves the way for `strata-bridge-poc` to use `strata` crates without patches/custom branches.
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update
-   [x] Refactor
-   [ ] Dependency update
-   [x] I have performed a self-review of my code.
-   [x] I have commented my code where necessary.
-   [x] I have updated the documentation if needed.
-   [x] My changes do not …
> chore(deps): bump to bitcoin 0.32.5

- Cargo.lock
- crates/tx-graph/src/connectors/connector_a31.rs
The current connector_a31 used a script inefficient version of SHA-256 implementation from the BitVM library. The `sha256` has been switched to `sha256_u4_stack`.
Closes: [STR-1083](https://alpenlabs.atlassian.net/browse/STR-1083)
[STR-1083]: https://alpenlabs.atlassian.net/browse/STR-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> STR-1083 : switch over to sha256_u4_stack.

- README.md
Hi! I fixes a dead link in the README.md file. The link to the SP1 Toolchain installation documentation was outdated and has been updated to the correct URL.
> fix: dead link README.md

- Cargo.toml
- crates/btc-notify/src/client.rs
- crates/btc-notify/src/event.rs
- crates/btc-notify/src/state_machine.rs
It has been in the backlog to have transaction events include block heights. It turns out that bip34 offers a consensus enforced way of getting this in the block data itself. It is brittle in the context of testnet4 and regtest right now. For that reason this implementation will set this value to zero if it cannot be recovered which confers a responsibility on the consumer to check for that for the time being.
Once rust-bitcoin 0.33.0 lands, this won't be necessary any longer since that is the first release where this bug will be fixed. For now we dodge the scenarios where this value isn't properly defined by enforcing that the test code doesn't use block heights between 0 and 16.
> add height support to transaction events

- bin/secret-service/src/seeded_impl/mod.rs
- bin/secret-service/src/seeded_impl/operator.rs
- bin/secret-service/src/seeded_impl/p2p.rs
- bin/secret-service/src/seeded_impl/paths.rs
This provides a fix for STR-1148 where the secret service wasn't using hardened paths due to some upstream issues in strata-key-derivation by hardcoding the paths.
> manual paths for p2p and operator keys

- crates/agent/src/operator.rs
- crates/bridge-proof/protocol/src/lib.rs
- crates/bridge-proof/protocol/src/statement.rs
- crates/primitives/src/params/connectors.rs
- crates/tx-graph/src/peg_out_graph.rs
- crates/tx-graph/src/transactions/assert_chain.rs
- crates/tx-graph/src/transactions/post_assert.rs
This PR:
* makes `wots::PublicKeys` a part of the `PegOutGraphInput` struct so that it corresponds more directly to `DepositSetup` message in `strata-p2p`.
* fixes a bug in the `agent` crate where the bitcoin chain segment only counted blocks after the last verified bitcoin height  for the given strata checkpoint.
> Move WOTS pubkeys to `PegOutGraphInput`

- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/predicates.rs
- crates/primitives/src/deposit.rs
- crates/primitives/src/scripts/general.rs
- crates/primitives/src/test_utils.rs
Adds the Stake index that is tied to a deposit transaction (DT) as the metadata in the DT inside the `OP_RETURN` as a 4-byte big-endian encoding.
This changes the `metadata_script` to take an `Option<&[u8; 4]>` as the stake index metadata. You can pass `None` for the DRT and `Some` for the DT.
STR-1177
> STR-1177: Adds Stake Index Metadata to Deposit Transaction `OP_RETURN`

- crates/btc-notify/src/client.rs
- crates/btc-notify/src/state_machine.rs
Added a bunch of logs as `trace!`/`debug!`/`warn!`/`info!`/`error!` etc to the `btc-notify` crate.
The in-line comments were really helpful.
I think I got most of it right, but let me know if I got something wrong.
None
> chore: logs for `btc-notify`

- Cargo.lock
- Cargo.toml
- bin/alpen-bridge/src/params.rs
- crates/duty-tracker/src/predicates.rs
- crates/params/src/default.rs
- crates/params/src/sidesystem.rs
- crates/params/src/tx_graph.rs
- crates/primitives/Cargo.toml
- crates/primitives/src/deposit.rs
- crates/primitives/src/errors.rs
- crates/primitives/src/scripts/general.rs
- crates/primitives/src/scripts/metadata.rs
- crates/primitives/src/scripts/mod.rs
- crates/primitives/src/scripts/prelude.rs
- crates/primitives/src/test_utils.rs
Deposit Request Transactions (DRT) now need X-Only PK of recovery address instead of take back leaf hash.
This fixes the DRT metadata OP_RETURN construction/parsing.
The new `OP_RETURN` now is:
1. magic bytes
2. Second Element:
a. DRT: 32-byte X-only PK for the recovery P2TR address
b. DT: 4-byte big-endian `u32` stake index
4. 20-byte EL address
This PR needs polishing. It is not ready, but the main ideas are here.
STR-1776
> feat!: DRT with X-Only PK metadata

- Cargo.lock
- Cargo.toml
- crates/duty-tracker/src/contract_manager.rs
- crates/p2p-service/Cargo.toml
- crates/p2p-service/src/bootstrap.rs
- crates/p2p-service/src/tests/common.rs
- crates/p2p-service/src/tests/request.rs
Updates the `strata-p2p` dependency that removes the database in the P2P (removing `threadpool` and `sled` deps) and also moving the responsibility of handling the get request messages to the duty tracker.
We need after this to implement the correct handling of get requests in the duty tracker (contract manager)
> chore(deps): update strata-p2p

- crates/duty-tracker/src/contract_manager.rs
adds a `warn` log if we receive gossip messages from an uknown MuSig2 txid.
Feel free to change the log message if you want
> log: warn if we see unknown gossip MuSig2 sessions

- crates/agent/src/operator.rs
- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/contract_state_machine.rs
- crates/duty-tracker/src/predicates.rs
- crates/operator-wallet/src/lib.rs
- crates/tx-graph/src/transactions/withdrawal_fulfillment.rs
Adds the withdraw fulfillment duty to the contract manager without broadcasting the transaction.
We are not broadcasting yet.
And we are making sure to not touch the CPFP UTXOs from the S2 General Wallet.
> contract manager: withdraw fulfillment

- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/predicates.rs
- crates/primitives/src/deposit.rs
- crates/primitives/src/operator_table.rs
Reconstructs the DRT from the `OP_RETURN` data in order to fully check that the DRT is compliant with the Strata Bridge specs.
I added some additional arguments to the `deposit_request_info` in `predicates` in order to reconstruct properly the DRT.
Also, I added some quality of life improvements to the `OperatorTable` to make it easier to get the aggregated pubkey and the BTC keys.
STR-1247
> STR-1247: fully check the DRT in predicates

- crates/bridge-proof/protocol/src/statement.rs
**Description:**
This pull request corrects a typo `withdrawal_fullfillment_idx` → `withdrawal_fulfillment_idx`. The changes ensure consistent and correct usage of the index throughout the code, improving clarity and maintainability.
> fix typo in `withdrawal_fulfillment` Index Handling

- Cargo.lock
- bin/dev-cli/Cargo.toml
- bin/dev-cli/src/bridge_in/deposit_request.rs
- crates/primitives/src/constants.rs
- crates/primitives/src/deposit.rs
- crates/primitives/src/scripts/metadata.rs
- crates/primitives/src/scripts/taproot.rs
- crates/tx-graph/Cargo.toml
- crates/tx-graph/src/transactions/disprove.rs
- crates/tx-graph/src/transactions/slash_stake.rs
This PR replaces the x-only public key in the deposit tx metadata with the merkle proof required to spend the DRT via the $$N/N$$ script spend path. This merkle proof is basically the hash of the take back script that can be used by the depositor to retrieve their funds should the deposit not succeed within a given time period.
> Replace x-only pk in dt metadata with merkle proof

- crates/agent/src/verifier.rs
- crates/bridge-proof/snark/src/prover.rs
> Update public input hash method of SP1 verifier

- .gitignore
- docker/gen_s2_tls.sh
- docker/vol/alpen-bridge-1/config.toml
- docker/vol/alpen-bridge-2/config.toml
- docker/vol/alpen-bridge-3/config.toml
- docker/vol/secret-service-1/config.toml
- docker/vol/secret-service-2/config.toml
- docker/vol/secret-service-3/config.toml
- scripts/ca-and-tls.sh
Changes the TLS certificate generation script to not convert into der and rather keep the pem encoded certs/keys.
> chore(tls) don't convert to der

- Cargo.lock
- bin/alpen-bridge/Cargo.toml
- bin/alpen-bridge/src/rpc_server.rs
- crates/db/src/inmemory/tracker.rs
- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/contract_persister.rs
- crates/duty-tracker/src/contract_state_machine.rs
- crates/primitives/src/duties.rs
- crates/rpc/src/traits.rs
- crates/rpc/src/types.rs
- migrations/20241113060253_init_schema.sql
Adds the RPC server that will grab a fresh state of the Contract Manager every 10 mins (block time) and cache it in-memory in a separate tokio thread. 
- Changed the table schema of the `contracts` table (Contract Manager) to match all the other ones in the SQL schema file. Cc @ProofOfKeags.
- Why 10 mins? Because on every new block, after it is processed, the contract manager serializes the whole state of all contracts in the `contracts` table.
- This PR is free of demons.
STR-1309
Closes #122
> STR-1309: Implement the RPC server V2

- Cargo.lock
- bin/alpen-bridge/src/config.rs
- bin/alpen-bridge/src/mode/operator.rs
- crates/p2p-service/src/bootstrap.rs
- crates/p2p-service/src/config.rs
- crates/p2p-service/src/tests/common.rs
- docker/vol/alpen-bridge-1/config.toml
- docker/vol/alpen-bridge-2/config.toml
- docker/vol/alpen-bridge-3/config.toml
In https://github.com/alpenlabs/strata-p2p/pull/62, we're adding a retry mechanism for the P2P to establish connections.
This PR adds the missing configs once the `strata-p2p` PR is merged.
Adds 3 new configs to the `P2PConfig`:
```toml
[p2p]
idle_connection_timeout = { secs = 1_000, nanos = 0 }
listening_addr = "/ip4/127.0.0.1/tcp/1234"
connect_to = ["/ip4/127.0.0.1/tcp/5678", "/ip4/127.0.0.1/tcp/9012"]
num_threads = 4
dial_timeout = { secs = 0, nanos = 250_000_000 }
general_timeout = { secs = 0, nanos = 250_000_000 }
connection_check_interval = { secs = 0, nanos = 500_000_000 }
```
STR-1337.
> fix(p2p): more fault-tolerant establish_connections

- crates/duty-tracker/src/contract_state_machine.rs
- crates/tx-graph/src/peg_out_graph.rs
- crates/tx-graph/src/pog_musig_functor.rs
This PR adds debug assertions to the warning logs in the CSM. This is helpful if we ever want to run the bridge in strict mode to get out ahead of potential issues, even if we think we know how to handle them.
This is based on #128 and so it should be reviewed after. I briefly tried to rebase it directly onto main but it's not worth it.
> MICRO: Chore/debug assert warnings

- bin/alpen-bridge/Cargo.toml
- bin/alpen-bridge/src/config.rs
- bin/alpen-bridge/src/constants.rs
- bin/alpen-bridge/src/mode/operator.rs
- bin/alpen-bridge/src/rpc_server.rs
- crates/duty-tracker/src/contract_persister.rs
- docker/vol/alpen-bridge-1/config.toml
- docker/vol/alpen-bridge-2/config.toml
- docker/vol/alpen-bridge-3/config.toml
- migrations/20241113060253_init_schema.sql
Turns out that the RPC server was trying to deserialize the `MachineState` as `ContractState`. That would never had worked.
The duty tracker serializes all the contracts:
```console
bridge-1-1          | 2025-05-14T19:13:20.780672Z DEBUG duty_tracker::contract_persister: committing all active contracts num_contracts=1
bridge-1-1          | 2025-05-14T19:13:40.848958Z  INFO alpen_bridge::rpc_server: initializing the RPC server initial contract cache fill before_num_contracts=1
bridge-1-1          | 2025-05-14T19:13:40.863640Z DEBUG alpen_bridge::rpc_server: Contracts cache refreshed after_num_contracts=1
```
STR-1344
> STR-1344: rpc state cache does not get updated

- Cargo.lock
- Cargo.toml
- bin/dev-cli/Cargo.toml
- bin/secret-service/Cargo.toml
- bin/secret-service/src/seeded_impl/wallet.rs
- bin/secret-service/src/tests.rs
- bridge-guest-builder/bridge-guest/Cargo.lock
- crates/agent/src/proof_interop.rs
- crates/bridge-proof/protocol/src/tx_info.rs
- crates/connectors/src/connector_c0.rs
- crates/duty-tracker/src/predicates.rs
- crates/tx-graph/src/peg_out_graph.rs
Why upgrading?
First, we should always upgrade.
Second, `0.32.5` has:
- `Psbt::sign` for taproot using `<PublicKey, SecretKey>` maps https://github.com/rust-bitcoin/rust-bitcoin/pull/4238
We can start to use PSBTs with Taproot since the bug with signing them with a pk<->sk map.
> chore(deps): bump bitcoin to 0.32.6

- .taplo.toml
- Cargo.lock
- bin/alpen-bridge/Cargo.toml
- bin/alpen-bridge/src/mode/operator.rs
- bin/alpen-bridge/src/rpc_server.rs
- crates/db/src/errors.rs
- crates/db/src/persistent/sqlite.rs
- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/contract_persister.rs
- migrations/20241113060253_init_schema.sql
- Makes all `ContractPersister` and RPC server DB operations robust by using `execute_with_retries` from `strata-bridge-db` crate.
- Commits all columns of the `contracts` table when serializing active contracts with the `ContractPersister`.
- Could not get `bincode`, `ciborium`, `postcard` or `rkyv` to play nice with the huge `MachineState` struct (that has a huge enum `ContractState` inside). So we're JSONing the 🖕🏻 thing as a quick fix.
- Adds the remaining RPC trait instantiations that were missing somehow.
Tested with multiple deposits, stopping restart nodes, and wait long enough to have the deposit confirmed.
STR-1342
> STR-1342: `io` error when loading contracts from disk upon restart

- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/contract_state_machine.rs
- crates/duty-tracker/src/executors/deposit.rs
Whenever we get nagged for a nonce or partial sig that we have already, we don't go through the secret service to get it again, instead we just publish the already known/generated one.
This PR:
1. Adds an `Option<PogMusigF<{PubNonce,PartialSignature}>>` field to `OperatorDuty::PublishGraph{Nonces,Signatures}` and an `Option<{PubNonce,PartialSignature}>` field to `OperatorDuty::PublishRoot{Nonce,Signature}`.
2. If we get nagged and we have our nonce or partial sig already in the `ContractState::Requested` enum variant, we fetch it and add as `Some` in the optional field in the duty.
3. When fulfilling the duty if the optional pre-existing field for nonce(s)/partial signature(s) is `Some`, then we bypass secret service client and just publish that thing again.
This avoids messing up with …
> STR-1318: Service `PubNonce`s, `AggNonce`s and `PartialSignature`s

- .github/actions/extract-rust-version/action.yml
- .github/workflows/build.yml
- .github/workflows/cron-nightly-rust.yml
- .github/workflows/dependencies.yml
- .github/workflows/docs.yml
- .github/workflows/lint-actions.yml
- .github/workflows/lint.yml
- .github/workflows/security.yml
- .github/workflows/unit.yml
CI jobs needs to specify a `toolchain` since `dtolnay/rust-toolchain` does not support `rust-toolchain.toml` (see https://github.com/dtolnay/rust-toolchain/issues/133).
This is annoying since we have manually sync the rust nightly version across multiple files, and also the damn thing is automatically updated every day 1.
This PR adds the feature for CI jobs to extract the nightly version from the `rust-toolchain.toml` using regex magic 🧙🏻 and saves the output in a ENV variable that can be used in further steps by the CI job to know which nightly version to use.
> ci: sync rust toolchain with `rust-toolchain.toml` file

- docker/alpen-bridge/Dockerfile
- docker/secret-service/Dockerfile
Removes hard-coded `memory_profiling` feature from bridge and secret service binaries' Dockerfiles.
Tested locally
> docker: remove `memory_profiling` build

- crates/duty-tracker/src/contract_actor.rs
Clarifies why we should only cleanup `ContractState::Resolved` and not `ContractState::Disproved` in `ContractActor`'s cleanups and also we can skip resolved contracts in the sync cursor calculation.
- Clarify `ContractActor`s cleanup: 2733c6ed14654bc867ea185d675fc2212570340b
- Skip resolved contracts in sync cursor calculation: 30d20b53d8d55db03822e7c0032f0a322c6ba257
STR-1529
> STR-1529: Completed contracts should also account for Disproven contracts

- Cargo.lock
- bin/alpen-bridge/src/rpc_server.rs
- crates/duty-tracker/src/contract_actor.rs
- crates/duty-tracker/src/contract_state_machine.rs
- crates/rpc/Cargo.toml
- crates/rpc/src/traits.rs
- crates/rpc/src/types.rs
On draft until #157 is merged.
This is what we need for the monitoring bridge API as pair coded with @krsnapaudel.
The twin PR in the `alpen-dashboards` is https://github.com/alpenlabs/alpen-dashboards/pull/25.
This PR also corrects the field `withdrawal_request_txid` in the `duty-tracker` to be a `Buf32` since it represents the transaction ID from the sidesystem (Reth) and NOT a Bitcoin transaction ID.
STR-919
> feat!(rpc): proper RPC traits and types for the monitoring API

- bin/alpen-bridge/src/rpc_server.rs
- crates/duty-tracker/src/contract_state_machine.rs
The `ContractState::Resolved` does not have a `claim_txid` field and this is needed for the bridge RPC monitoring API.
Also none of the post-`Assigned` states have the `withdraw_request_txid` which is also needed for the bridge RPC monitoring API.
Light breaking since it adds a new field to enum variants.
STR-1560
> feat!: add claim and withdraw data to `ContractState`s past `Assigned`

- Cargo.lock
- Cargo.toml
- bin/alpen-bridge/Cargo.toml
- bin/alpen-bridge/src/config.rs
- bin/alpen-bridge/src/main.rs
- bin/alpen-bridge/src/mode/operator.rs
- bin/alpen-bridge/src/mode/verifier.rs
- crates/duty-tracker/Cargo.toml
- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/errors.rs
- crates/duty-tracker/src/lib.rs
- crates/duty-tracker/src/shutdown.rs
Implements graceful shutdown for the bridge node that persists critical state before termination. When shutdown signals are received, the system extracts active contracts, claim txids, and stake chain data, then persists them to disk before shutting down.
The key changes:
- Adds a new `shutdown` module that uses `strata-tasks` to handle persistence critical in-memory state before shutdown.
- Replaces the `contract_manager` module `ExecutionState` for the new `shutdown` module `ExecutionState`.
- Modifies `alpen-bridge` to use the new shutdown system.
The shutdown flow: Signal → Extract state → Persist to disk → Exit
As always, the commits are linear and somewhat atomic. So this PR is commit-review-friendly.
STR-1497
> feat: graceful shutdown

- .gitignore
- .justfile
- bin/alpen-bridge/src/main.rs
- bin/mock-checkpoint/README.md
- crates/duty-tracker/src/executors/deposit.rs
- crates/duty-tracker/src/executors/optimistic_withdrawal.rs
- crates/operator-wallet/src/lib.rs
- docker/bitcoin/entrypoint.sh
- docker/vol/alpen-bridge-1/config.toml
- docker/vol/alpen-bridge-2/config.toml
- docker/vol/alpen-bridge-3/config.toml
This PR fixes an issue with withdrawal execution where if two withdrawal fufillment duties were created together, the second one would not be executed until the first withdrawal fulfillment transaction had been buried. This can also cause delays in publishing the deposit setup message. The cause of this issue is that in both cases, we first try to sync the operator wallet which requires that we obtain a `WriteLock` on the operator wallet. This lock is held until the transaction is buried. This PR fixes this by releasing the lock on the wallet as soon as possible and tracking the used funding utxos in memory so that two withdrawal fulfillment execution threads running in parallel do not end up using the same funding utxo.
**Auxiliary Fixes**
- Fixes the bridge binary to actually use the …
> STR-1561 execute withdrawal fulfillments in parallel

- crates/duty-tracker/src/executors/deposit.rs
- crates/tx-graph/src/transactions/deposit.rs
Normalize all `TapSighashesType`s to `Default` since we can save 1 byte in all transactions.
Merge together with https://github.com/alpenlabs/alpen/pull/934.
STR-1581
> fix: change all taproot sighashes to `Default` and better parsing

- bin/alpen-bridge/src/rpc_server.rs
- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/contract_state_machine.rs
Implements non-crashing abort behavior if deposit transaction isn't issued before the abort deadline.
This is a super simple change just to make sure we don't crash if we ever abort a contract. Right now we do nothing and we keep these contracts around indefinitely. This technically constitutes a resource leak but it will not be an issue to begin with. The change needed to get rid of the resource leak is pruning "active" Aborted contracts once their deposit index has been surpassed by the stake chain height.
Make sure I didn't forget anything in the state transition rules that would prevent the stake transaction from being published. CC @Rajil1213.
> STR-1502: Abort Contracts

- crates/duty-tracker/src/contract_manager.rs
turns out this code would *never* persist contract state after deposit setup processing. This means that we would lose this state if a node went down.
> duty-tracker: actually persist deposit setup duties on time

- bin/alpen-bridge/src/config.rs
- bin/alpen-bridge/src/mode/operator.rs
- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/executors/config.rs
- crates/duty-tracker/src/executors/mod.rs
- crates/duty-tracker/src/executors/optimistic_withdrawal.rs
- crates/p2p-service/src/message_handler.rs
- docker/vol/alpen-bridge-1/config.toml
- docker/vol/alpen-bridge-2/config.toml
- docker/vol/alpen-bridge-3/config.toml
This PR makes the retry logic for publishing stake transactions configurable. Previously, this logic was hardcoded to retry 25 times with a 1-minute delay. This is not suitable for all environments where the signet block times may be different. Furthermore, the value 25 was chosen because it is the descendant limit for version-2 transactions but for version-3 transactions, the limit is just 2, which means that retrying is futile until a new block is created. Making the retry logic configurable is the most straightforward way to address this issue.
Closes STR-1589
> STR-1509 Make retry logic for publishing stake txs configurable

- bin/mock-checkpoint/src/chainstate.rs
There was a wrong assumption about how the mock deposit entries can be populated in the mock chainstate. This PR fixes that.
> (mock-checkpoint): Fix deposit entries populating in chainstate

- .justfile
- crates/db/src/inmemory/public.rs
- crates/db/src/persistent/models.rs
- crates/db/src/persistent/sqlite.rs
- crates/db/src/public.rs
- crates/duty-tracker/src/contract_manager.rs
- crates/duty-tracker/src/contract_state_machine.rs
- crates/duty-tracker/src/errors.rs
- crates/duty-tracker/src/stake_chain_persister.rs
- crates/duty-tracker/src/stake_chain_state_machine.rs
- crates/stake-chain/Cargo.toml
- crates/stake-chain/src/stake_chain.rs
- docker/vol/alpen-bridge-1/config.toml
- docker/vol/alpen-bridge-2/config.toml
- docker/vol/alpen-bridge-3/config.toml
This PR fixes an issue where a node would not be able to make progress under the following circumstances:
1. The node goes down _after_ persisting a new contract but _before_ persisting the corresponding stake data.
2. While down, one or more deposit requests are made.
3. When the node comes back up, the node crashes as the lagged blocks are processed first and without the stake data (that couldn't be persisted before the crash), the deposit requests cannot be processed as the stake chain has a discontinuity.
This fix involves the following changes:
1. We now don't crash when we fail to process an ouroboros message so that we let things run their course and reach eventual consistency.
2. We also nag if the stake data is missing for a contract that has been persisted since this data is …
> fix: handle node going down before persisting stake data and missing deposit requests

- bin/alpen-bridge/src/rpc_server.rs
- crates/rpc/src/types.rs
adds `claim_txid` for `Resolved` contracts in the `claims` RPC method.
Slightly breaking because removing `claim_txid` from `RpcReimbursementStatus` since that information is already available in the `RpcClaimInfo`. Heads-up @krsnapaudel!
STR-1625
> fix!(alpen-bridge): missing RPC claim information for `Resolved` contracts
